// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvXLZJAyKAVQqpNG5UKctI8lANRywRvEI',
    appId: '1:28355678117:web:4fe44fc38142ad3367624c',
    messagingSenderId: '28355678117',
    projectId: 'ecosphere-20f5d',
    authDomain: 'ecosphere-20f5d.firebaseapp.com',
    storageBucket: 'ecosphere-20f5d.appspot.com',
    measurementId: 'G-17ZJ3ZKBH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU3TBk34YPwyaR_1QAIVlke0Ka-Y-PKX8',
    appId: '1:28355678117:android:08e748a75c6817f067624c',
    messagingSenderId: '28355678117',
    projectId: 'ecosphere-20f5d',
    storageBucket: 'ecosphere-20f5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVuC4uCCk-KX7BZ9U1pZVUtxEK7bYlO8E',
    appId: '1:28355678117:ios:03a2a0a9b4e0a1ed67624c',
    messagingSenderId: '28355678117',
    projectId: 'ecosphere-20f5d',
    storageBucket: 'ecosphere-20f5d.appspot.com',
    iosBundleId: 'com.example.ecosphere',
  );
}
